name: CI/CD Pipeline for Nuxt.js with Yarn

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Shallow clone for speed

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Updated to Node 18

      - name: Install Yarn
        run: npm install -g yarn

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies with Yarn
        run: yarn install --frozen-lockfile

      - name: Build Nuxt.js app for production
        run: yarn run build

      - name: Prepare production files
        run: yarn run generate

      - name: Debug runner environment
        run: |
          echo "Runner version: $RUNNER_VERSION"
          echo "GitHub API status: $(curl -s https://api.github.com -o /dev/null -w '%{http_code}')"
          echo "Access to upload-artifact: $(curl -s -I https://github.com/actions/upload-artifact -o /dev/null -w '%{http_code}')"
          ls -la dist/

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuxt-dist
          path: dist/
          retention-days: 1  # Short retention since it’s just for deploy

  deploy:
    runs-on: self-hosted
    needs: build
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download production artifacts
        uses: actions/download-artifact@v4
        with:
          name: nuxt-dist  # Fixed typo from previous version
          path: dist/
